version: "3.0"
services:
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

    environment:
       SERVER_NAME: "elasticsearch"
       xpack.security.enabled: 'false'
       discovery.type: "single-node" 
       ES_JAVA_OPTS: "-Xmx300m"
       http.cors.enabled : 'true'
       http.cors.allow-origin : "*" 
       http.cors.allow-methods : OPTIONS, HEAD, GET, POST, PUT, DELETE
       http.cors.allow-headers : X-Requested-With,X-Auth-Token,Content-Type, Content-Length

    networks:
      - es-net
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:8.1.2
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601
  dejavu:
    image: appbaseio/dejavu
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    networks:
      - es-net
    depends_on:
      - elasticsearch
    ports:
      - 1358:1358
networks:
  es-net:
    driver: bridge
